name: Run Selenium Script

#on: [push]                # Commit changes하면 워크플로우가 바로 실행
on:
  workflow_dispatch:       # Actions 탭에서 직접 [Run workflow] 버튼을 눌러야만 실행

jobs:
  selenium-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Install Chromium
        run: sudo apt-get install -y chromium-browser

      - name: Run script
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
        run: python lotteon1.py

      - name: Upload results
        uses: actions/upload-artifact@v3
        with:
          name: price-results
          path: output.txt
